export const CREATE_STUDENT = "CREATE_STUDENT";
export const RETRIEVE_STUDENT = "RETRIEVE_STUDENT";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const DELETE_ALL_STUDENT = "DELETE_ALL_STUDENT";